# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='order_id',
        ),
    ]
