# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-05 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAndRegister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='desciption',
            new_name='description',
        ),
    ]
