# Generated by Django 2.1.2 on 2018-10-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginAndRegister', '0002_auto_20181005_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('itemName', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('desciption', models.TextField()),
                ('inventory', models.IntegerField()),
                ('quantitySold', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('upload', models.ImageField(upload_to='product_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='LoginAndRegister.User')),
            ],
        ),
    ]
