# Generated by Django 2.1.2 on 2018-10-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0002_auto_20181029_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='upload',
        ),
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.ImageField(default=1, upload_to='product_image/'),
            preserve_default=False,
        ),
    ]
