# Generated by Django 2.1.2 on 2018-10-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0003_auto_20181029_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload',
            field=models.ImageField(blank=True, upload_to='product_image/'),
        ),
    ]
