# Generated by Django 2.1.2 on 2018-10-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0005_remove_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desciption',
            new_name='description',
        ),
    ]
