# Generated by Django 2.1.2 on 2018-10-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0006_auto_20181029_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='AdminDashboard.Product'),
        ),
    ]
