# Generated by Django 2.1.2 on 2018-11-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0010_auto_20181101_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='category',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='category',
            field=models.ManyToManyField(related_name='inventory_product', to='AdminDashboard.Category'),
        ),
    ]
