# Generated by Django 2.1.2 on 2018-11-01 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0011_auto_20181101_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='category',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='AdminDashboard.Category'),
            preserve_default=False,
        ),
    ]
