# Generated by Django 2.1.2 on 2018-11-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0013_auto_20181101_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='inventory_product',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_category', to='AdminDashboard.Category'),
            preserve_default=False,
        ),
    ]
